export type TeamUpPost = {
  docId?: string | undefined;
  name: string | undefined;
  username: string;
  uid: string;
  photoURL: string | undefined;
  gameCode: string | undefined;
  mode: string | undefined;
  perspective?: string | undefined;
  tier?: string | undefined;
  kd: string | undefined;
  averageDamage: string | undefined;
  age: string | undefined;
  experience: string | undefined;
  role: string | undefined;
  purpose: string | undefined;
  timeAvailability: string | undefined;
  language: string | undefined;
  description: string | undefined;
};
