import Head from 'next/head';
import ChatContainer from '../../components/Contact/ChatContainer';
import TypeContainer from '../../components/Contact/TypeContainer';

export default function Home() {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <main>
        <h1 className="text-xl font-semibold text-gray-600 mb-4">
          Please ask all your queries here
        </h1>
        <div className="px-4 border-4 rounded-md min-h-full">
          <ChatContainer />
          <TypeContainer />
        </div>
      </main>
    </div>
  );
}
