import { FC } from 'react';
import Head from 'next/head';
import TabNavigator from '../../Navigation/TabNavigation/TabNavigator';
import Aux from '../../../hoc/Auxiliary/Auxiliary';
import { useAuth } from '../../../context/authContext';
import { OrgFormData } from '../../../utilities/organization/types';
import LocationIcon from '../../UI/Icons/TournamentIcons/LocationIcon';

type Props = {
  data: OrgFormData;
};

const HeaderOrg: FC<Props> = ({ data }: Props) => {
  const {
    userData: { linkedOrganizationId },
  } = useAuth();

  const TABS = [
    {
      label: 'Events',
      href: `/organization/${linkedOrganizationId}/tournaments`,
      pathName: '/organization/[orgId]/tournaments',
    },
    {
      label: 'About',
      href: `/organization/${linkedOrganizationId}`,
      pathName: '/organization/[orgId]',
    },
  ];

  return (
    <Aux>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <div className="flex flex-row xl:w-2/3 md:w-5/6 mx-auto px-4 md:px-0 my-8">
        <div className="flex w-16 h-16 bg-indigo-600 rounded-full items-center my-auto">
          <span className="self-center text-5xl font-bold tracking-wide text-gray-900 font-sans m-auto">
            {data.name[0]}
          </span>
        </div>
        <div className="ml-5">
          <span className="text-gray-300 text-2xl font-semibold font-sans ml-2">
            {data.name}
          </span>
          <div className="flex flex-row mt-4">
            <LocationIcon
              size={25}
              className={'fill-current text-indigo-400'}
            />
            <span className="text-gray-400 text-lg ml-2 font-sans">
              {data.location}
            </span>
          </div>
        </div>
      </div>
      <TabNavigator tabs={TABS} />
    </Aux>
  );
};

export default HeaderOrg;
