import Head from 'next/head';
import TabNavigator from '../../../components/Navigation/OrgNavigation/TabNavigator';
import Aux from '../../../hoc/Auxiliary/Auxiliary';

export default function OrganizationAdmin() {
  const id = 1;

  return (
    <Aux>
      <Head>
        <title>Seven Esports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabNavigator tabNumber={0} />
    </Aux>
  );
}
