import Head from 'next/head';
import TabNavigator from '../../../components/Navigation/OrgNavigation/TabNavigator';
import Aux from '../../../hoc/Auxiliary/Auxiliary';

export default function Tournaments() {
  return (
    <Aux>
      <Head>
        <title>Seven Esports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabNavigator tabNumber={1} />
      <div>Create Tournament</div>
    </Aux>
  );
}
