export const countries = [
  {
    name: 'Afghanistan',
    alpha2Code: 'AF',
    callingCodes: ['93'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+04:30'],
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    name: 'Åland Islands',
    alpha2Code: 'AX',
    callingCodes: ['358'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    name: 'Albania',
    alpha2Code: 'AL',
    callingCodes: ['355'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/alb.svg',
  },
  {
    name: 'Algeria',
    alpha2Code: 'DZ',
    callingCodes: ['213'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/dza.svg',
  },
  {
    name: 'American Samoa',
    alpha2Code: 'AS',
    callingCodes: ['1684'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC-11:00'],
    flag: 'https://restcountries.eu/data/asm.svg',
  },
  {
    name: 'Andorra',
    alpha2Code: 'AD',
    callingCodes: ['376'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/and.svg',
  },
  {
    name: 'Angola',
    alpha2Code: 'AO',
    callingCodes: ['244'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/ago.svg',
  },
  {
    name: 'Anguilla',
    alpha2Code: 'AI',
    callingCodes: ['1264'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/aia.svg',
  },
  {
    name: 'Antarctica',
    alpha2Code: 'AQ',
    callingCodes: ['672'],
    region: 'Polar',
    subregion: '',
    timezones: [
      'UTC-03:00',
      'UTC+03:00',
      'UTC+05:00',
      'UTC+06:00',
      'UTC+07:00',
      'UTC+08:00',
      'UTC+10:00',
      'UTC+12:00',
    ],
    flag: 'https://restcountries.eu/data/ata.svg',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
    callingCodes: ['1268'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/atg.svg',
  },
  {
    name: 'Argentina',
    alpha2Code: 'AR',
    callingCodes: ['54'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-03:00'],
    flag: 'https://restcountries.eu/data/arg.svg',
  },
  {
    name: 'Armenia',
    alpha2Code: 'AM',
    callingCodes: ['374'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+04:00'],
    flag: 'https://restcountries.eu/data/arm.svg',
  },
  {
    name: 'Aruba',
    alpha2Code: 'AW',
    callingCodes: ['297'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/abw.svg',
  },
  {
    name: 'Australia',
    alpha2Code: 'AU',
    callingCodes: ['61'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    timezones: [
      'UTC+05:00',
      'UTC+06:30',
      'UTC+07:00',
      'UTC+08:00',
      'UTC+09:30',
      'UTC+10:00',
      'UTC+10:30',
      'UTC+11:30',
    ],
    flag: 'https://restcountries.eu/data/aus.svg',
  },
  {
    name: 'Austria',
    alpha2Code: 'AT',
    callingCodes: ['43'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/aut.svg',
  },
  {
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
    callingCodes: ['994'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+04:00'],
    flag: 'https://restcountries.eu/data/aze.svg',
  },
  {
    name: 'Bahamas',
    alpha2Code: 'BS',
    callingCodes: ['1242'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/bhs.svg',
  },
  {
    name: 'Bahrain',
    alpha2Code: 'BH',
    callingCodes: ['973'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/bhr.svg',
  },
  {
    name: 'Bangladesh',
    alpha2Code: 'BD',
    callingCodes: ['880'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+06:00'],
    flag: 'https://restcountries.eu/data/bgd.svg',
  },
  {
    name: 'Barbados',
    alpha2Code: 'BB',
    callingCodes: ['1246'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/brb.svg',
  },
  {
    name: 'Belarus',
    alpha2Code: 'BY',
    callingCodes: ['375'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/blr.svg',
  },
  {
    name: 'Belgium',
    alpha2Code: 'BE',
    callingCodes: ['32'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/bel.svg',
  },
  {
    name: 'Belize',
    alpha2Code: 'BZ',
    callingCodes: ['501'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-06:00'],
    flag: 'https://restcountries.eu/data/blz.svg',
  },
  {
    name: 'Benin',
    alpha2Code: 'BJ',
    callingCodes: ['229'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/ben.svg',
  },
  {
    name: 'Bermuda',
    alpha2Code: 'BM',
    callingCodes: ['1441'],
    region: 'Americas',
    subregion: 'Northern America',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/bmu.svg',
  },
  {
    name: 'Bhutan',
    alpha2Code: 'BT',
    callingCodes: ['975'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+06:00'],
    flag: 'https://restcountries.eu/data/btn.svg',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha2Code: 'BO',
    callingCodes: ['591'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/bol.svg',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2Code: 'BQ',
    callingCodes: ['5997'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/bes.svg',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
    callingCodes: ['387'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/bih.svg',
  },
  {
    name: 'Botswana',
    alpha2Code: 'BW',
    callingCodes: ['267'],
    region: 'Africa',
    subregion: 'Southern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/bwa.svg',
  },
  {
    name: 'Bouvet Island',
    alpha2Code: 'BV',
    callingCodes: [''],
    region: '',
    subregion: '',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/bvt.svg',
  },
  {
    name: 'Brazil',
    alpha2Code: 'BR',
    callingCodes: ['55'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
    flag: 'https://restcountries.eu/data/bra.svg',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
    callingCodes: ['246'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+06:00'],
    flag: 'https://restcountries.eu/data/iot.svg',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
    callingCodes: [''],
    region: 'Americas',
    subregion: 'Northern America',
    timezones: ['UTC-11:00', 'UTC-10:00', 'UTC+12:00'],
    flag: 'https://restcountries.eu/data/umi.svg',
  },
  {
    name: 'Virgin Islands (British)',
    alpha2Code: 'VG',
    callingCodes: ['1284'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/vgb.svg',
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2Code: 'VI',
    callingCodes: ['1 340'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/vir.svg',
  },
  {
    name: 'Brunei Darussalam',
    alpha2Code: 'BN',
    callingCodes: ['673'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/brn.svg',
  },
  {
    name: 'Bulgaria',
    alpha2Code: 'BG',
    callingCodes: ['359'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/bgr.svg',
  },
  {
    name: 'Burkina Faso',
    alpha2Code: 'BF',
    callingCodes: ['226'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/bfa.svg',
  },
  {
    name: 'Burundi',
    alpha2Code: 'BI',
    callingCodes: ['257'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/bdi.svg',
  },
  {
    name: 'Cambodia',
    alpha2Code: 'KH',
    callingCodes: ['855'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+07:00'],
    flag: 'https://restcountries.eu/data/khm.svg',
  },
  {
    name: 'Cameroon',
    alpha2Code: 'CM',
    callingCodes: ['237'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/cmr.svg',
  },
  {
    name: 'Canada',
    alpha2Code: 'CA',
    callingCodes: ['1'],
    region: 'Americas',
    subregion: 'Northern America',
    timezones: [
      'UTC-08:00',
      'UTC-07:00',
      'UTC-06:00',
      'UTC-05:00',
      'UTC-04:00',
      'UTC-03:30',
    ],
    flag: 'https://restcountries.eu/data/can.svg',
  },
  {
    name: 'Cabo Verde',
    alpha2Code: 'CV',
    callingCodes: ['238'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC-01:00'],
    flag: 'https://restcountries.eu/data/cpv.svg',
  },
  {
    name: 'Cayman Islands',
    alpha2Code: 'KY',
    callingCodes: ['1345'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/cym.svg',
  },
  {
    name: 'Central African Republic',
    alpha2Code: 'CF',
    callingCodes: ['236'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/caf.svg',
  },
  {
    name: 'Chad',
    alpha2Code: 'TD',
    callingCodes: ['235'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/tcd.svg',
  },
  {
    name: 'Chile',
    alpha2Code: 'CL',
    callingCodes: ['56'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-06:00', 'UTC-04:00'],
    flag: 'https://restcountries.eu/data/chl.svg',
  },
  {
    name: 'China',
    alpha2Code: 'CN',
    callingCodes: ['86'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/chn.svg',
  },
  {
    name: 'Christmas Island',
    alpha2Code: 'CX',
    callingCodes: ['61'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    timezones: ['UTC+07:00'],
    flag: 'https://restcountries.eu/data/cxr.svg',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
    callingCodes: ['61'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    timezones: ['UTC+06:30'],
    flag: 'https://restcountries.eu/data/cck.svg',
  },
  {
    name: 'Colombia',
    alpha2Code: 'CO',
    callingCodes: ['57'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/col.svg',
  },
  {
    name: 'Comoros',
    alpha2Code: 'KM',
    callingCodes: ['269'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/com.svg',
  },
  {
    name: 'Congo',
    alpha2Code: 'CG',
    callingCodes: ['242'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/cog.svg',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    alpha2Code: 'CD',
    callingCodes: ['243'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00', 'UTC+02:00'],
    flag: 'https://restcountries.eu/data/cod.svg',
  },
  {
    name: 'Cook Islands',
    alpha2Code: 'CK',
    callingCodes: ['682'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC-10:00'],
    flag: 'https://restcountries.eu/data/cok.svg',
  },
  {
    name: 'Costa Rica',
    alpha2Code: 'CR',
    callingCodes: ['506'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-06:00'],
    flag: 'https://restcountries.eu/data/cri.svg',
  },
  {
    name: 'Croatia',
    alpha2Code: 'HR',
    callingCodes: ['385'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/hrv.svg',
  },
  {
    name: 'Cuba',
    alpha2Code: 'CU',
    callingCodes: ['53'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/cub.svg',
  },
  {
    name: 'Curaçao',
    alpha2Code: 'CW',
    callingCodes: ['599'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/cuw.svg',
  },
  {
    name: 'Cyprus',
    alpha2Code: 'CY',
    callingCodes: ['357'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/cyp.svg',
  },
  {
    name: 'Czech Republic',
    alpha2Code: 'CZ',
    callingCodes: ['420'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/cze.svg',
  },
  {
    name: 'Denmark',
    alpha2Code: 'DK',
    callingCodes: ['45'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC-04:00', 'UTC-03:00', 'UTC-01:00', 'UTC', 'UTC+01:00'],
    flag: 'https://restcountries.eu/data/dnk.svg',
  },
  {
    name: 'Djibouti',
    alpha2Code: 'DJ',
    callingCodes: ['253'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/dji.svg',
  },
  {
    name: 'Dominica',
    alpha2Code: 'DM',
    callingCodes: ['1767'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/dma.svg',
  },
  {
    name: 'Dominican Republic',
    alpha2Code: 'DO',
    callingCodes: ['1809', '1829', '1849'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/dom.svg',
  },
  {
    name: 'Ecuador',
    alpha2Code: 'EC',
    callingCodes: ['593'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-06:00', 'UTC-05:00'],
    flag: 'https://restcountries.eu/data/ecu.svg',
  },
  {
    name: 'Egypt',
    alpha2Code: 'EG',
    callingCodes: ['20'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/egy.svg',
  },
  {
    name: 'El Salvador',
    alpha2Code: 'SV',
    callingCodes: ['503'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-06:00'],
    flag: 'https://restcountries.eu/data/slv.svg',
  },
  {
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
    callingCodes: ['240'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/gnq.svg',
  },
  {
    name: 'Eritrea',
    alpha2Code: 'ER',
    callingCodes: ['291'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/eri.svg',
  },
  {
    name: 'Estonia',
    alpha2Code: 'EE',
    callingCodes: ['372'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/est.svg',
  },
  {
    name: 'Ethiopia',
    alpha2Code: 'ET',
    callingCodes: ['251'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/eth.svg',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2Code: 'FK',
    callingCodes: ['500'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/flk.svg',
  },
  {
    name: 'Faroe Islands',
    alpha2Code: 'FO',
    callingCodes: ['298'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+00:00'],
    flag: 'https://restcountries.eu/data/fro.svg',
  },
  {
    name: 'Fiji',
    alpha2Code: 'FJ',
    callingCodes: ['679'],
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: ['UTC+12:00'],
    flag: 'https://restcountries.eu/data/fji.svg',
  },
  {
    name: 'Finland',
    alpha2Code: 'FI',
    callingCodes: ['358'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/fin.svg',
  },
  {
    name: 'France',
    alpha2Code: 'FR',
    callingCodes: ['33'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: [
      'UTC-10:00',
      'UTC-09:30',
      'UTC-09:00',
      'UTC-08:00',
      'UTC-04:00',
      'UTC-03:00',
      'UTC+01:00',
      'UTC+03:00',
      'UTC+04:00',
      'UTC+05:00',
      'UTC+11:00',
      'UTC+12:00',
    ],
    flag: 'https://restcountries.eu/data/fra.svg',
  },
  {
    name: 'French Guiana',
    alpha2Code: 'GF',
    callingCodes: ['594'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-03:00'],
    flag: 'https://restcountries.eu/data/guf.svg',
  },
  {
    name: 'French Polynesia',
    alpha2Code: 'PF',
    callingCodes: ['689'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC-10:00', 'UTC-09:30', 'UTC-09:00'],
    flag: 'https://restcountries.eu/data/pyf.svg',
  },
  {
    name: 'French Southern Territories',
    alpha2Code: 'TF',
    callingCodes: [''],
    region: 'Africa',
    subregion: 'Southern Africa',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/atf.svg',
  },
  {
    name: 'Gabon',
    alpha2Code: 'GA',
    callingCodes: ['241'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/gab.svg',
  },
  {
    name: 'Gambia',
    alpha2Code: 'GM',
    callingCodes: ['220'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC+00:00'],
    flag: 'https://restcountries.eu/data/gmb.svg',
  },
  {
    name: 'Georgia',
    alpha2Code: 'GE',
    callingCodes: ['995'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/geo.svg',
  },
  {
    name: 'Germany',
    alpha2Code: 'DE',
    callingCodes: ['49'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/deu.svg',
  },
  {
    name: 'Ghana',
    alpha2Code: 'GH',
    callingCodes: ['233'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/gha.svg',
  },
  {
    name: 'Gibraltar',
    alpha2Code: 'GI',
    callingCodes: ['350'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/gib.svg',
  },
  {
    name: 'Greece',
    alpha2Code: 'GR',
    callingCodes: ['30'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/grc.svg',
  },
  {
    name: 'Greenland',
    alpha2Code: 'GL',
    callingCodes: ['299'],
    region: 'Americas',
    subregion: 'Northern America',
    timezones: ['UTC-04:00', 'UTC-03:00', 'UTC-01:00', 'UTC+00:00'],
    flag: 'https://restcountries.eu/data/grl.svg',
  },
  {
    name: 'Grenada',
    alpha2Code: 'GD',
    callingCodes: ['1473'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/grd.svg',
  },
  {
    name: 'Guadeloupe',
    alpha2Code: 'GP',
    callingCodes: ['590'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/glp.svg',
  },
  {
    name: 'Guam',
    alpha2Code: 'GU',
    callingCodes: ['1671'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+10:00'],
    flag: 'https://restcountries.eu/data/gum.svg',
  },
  {
    name: 'Guatemala',
    alpha2Code: 'GT',
    callingCodes: ['502'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-06:00'],
    flag: 'https://restcountries.eu/data/gtm.svg',
  },
  {
    name: 'Guernsey',
    alpha2Code: 'GG',
    callingCodes: ['44'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+00:00'],
    flag: 'https://restcountries.eu/data/ggy.svg',
  },
  {
    name: 'Guinea',
    alpha2Code: 'GN',
    callingCodes: ['224'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/gin.svg',
  },
  {
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
    callingCodes: ['245'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/gnb.svg',
  },
  {
    name: 'Guyana',
    alpha2Code: 'GY',
    callingCodes: ['592'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/guy.svg',
  },
  {
    name: 'Haiti',
    alpha2Code: 'HT',
    callingCodes: ['509'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/hti.svg',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
    callingCodes: [''],
    region: '',
    subregion: '',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/hmd.svg',
  },
  {
    name: 'Holy See',
    alpha2Code: 'VA',
    callingCodes: ['379'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/vat.svg',
  },
  {
    name: 'Honduras',
    alpha2Code: 'HN',
    callingCodes: ['504'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-06:00'],
    flag: 'https://restcountries.eu/data/hnd.svg',
  },
  {
    name: 'Hong Kong',
    alpha2Code: 'HK',
    callingCodes: ['852'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/hkg.svg',
  },
  {
    name: 'Hungary',
    alpha2Code: 'HU',
    callingCodes: ['36'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/hun.svg',
  },
  {
    name: 'Iceland',
    alpha2Code: 'IS',
    callingCodes: ['354'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/isl.svg',
  },
  {
    name: 'India',
    alpha2Code: 'IN',
    callingCodes: ['91'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+05:30'],
    flag: 'https://restcountries.eu/data/ind.svg',
  },
  {
    name: 'Indonesia',
    alpha2Code: 'ID',
    callingCodes: ['62'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+07:00', 'UTC+08:00', 'UTC+09:00'],
    flag: 'https://restcountries.eu/data/idn.svg',
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: 'CI',
    callingCodes: ['225'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/civ.svg',
  },
  {
    name: 'Iran (Islamic Republic of)',
    alpha2Code: 'IR',
    callingCodes: ['98'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+03:30'],
    flag: 'https://restcountries.eu/data/irn.svg',
  },
  {
    name: 'Iraq',
    alpha2Code: 'IQ',
    callingCodes: ['964'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/irq.svg',
  },
  {
    name: 'Ireland',
    alpha2Code: 'IE',
    callingCodes: ['353'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/irl.svg',
  },
  {
    name: 'Isle of Man',
    alpha2Code: 'IM',
    callingCodes: ['44'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+00:00'],
    flag: 'https://restcountries.eu/data/imn.svg',
  },
  {
    name: 'Israel',
    alpha2Code: 'IL',
    callingCodes: ['972'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/isr.svg',
  },
  {
    name: 'Italy',
    alpha2Code: 'IT',
    callingCodes: ['39'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/ita.svg',
  },
  {
    name: 'Jamaica',
    alpha2Code: 'JM',
    callingCodes: ['1876'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/jam.svg',
  },
  {
    name: 'Japan',
    alpha2Code: 'JP',
    callingCodes: ['81'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+09:00'],
    flag: 'https://restcountries.eu/data/jpn.svg',
  },
  {
    name: 'Jersey',
    alpha2Code: 'JE',
    callingCodes: ['44'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/jey.svg',
  },
  {
    name: 'Jordan',
    alpha2Code: 'JO',
    callingCodes: ['962'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/jor.svg',
  },
  {
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
    callingCodes: ['76', '77'],
    region: 'Asia',
    subregion: 'Central Asia',
    timezones: ['UTC+05:00', 'UTC+06:00'],
    flag: 'https://restcountries.eu/data/kaz.svg',
  },
  {
    name: 'Kenya',
    alpha2Code: 'KE',
    callingCodes: ['254'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/ken.svg',
  },
  {
    name: 'Kiribati',
    alpha2Code: 'KI',
    callingCodes: ['686'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+12:00', 'UTC+13:00', 'UTC+14:00'],
    flag: 'https://restcountries.eu/data/kir.svg',
  },
  {
    name: 'Kuwait',
    alpha2Code: 'KW',
    callingCodes: ['965'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/kwt.svg',
  },
  {
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
    callingCodes: ['996'],
    region: 'Asia',
    subregion: 'Central Asia',
    timezones: ['UTC+06:00'],
    flag: 'https://restcountries.eu/data/kgz.svg',
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: 'LA',
    callingCodes: ['856'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+07:00'],
    flag: 'https://restcountries.eu/data/lao.svg',
  },
  {
    name: 'Latvia',
    alpha2Code: 'LV',
    callingCodes: ['371'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/lva.svg',
  },
  {
    name: 'Lebanon',
    alpha2Code: 'LB',
    callingCodes: ['961'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/lbn.svg',
  },
  {
    name: 'Lesotho',
    alpha2Code: 'LS',
    callingCodes: ['266'],
    region: 'Africa',
    subregion: 'Southern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/lso.svg',
  },
  {
    name: 'Liberia',
    alpha2Code: 'LR',
    callingCodes: ['231'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/lbr.svg',
  },
  {
    name: 'Libya',
    alpha2Code: 'LY',
    callingCodes: ['218'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/lby.svg',
  },
  {
    name: 'Liechtenstein',
    alpha2Code: 'LI',
    callingCodes: ['423'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/lie.svg',
  },
  {
    name: 'Lithuania',
    alpha2Code: 'LT',
    callingCodes: ['370'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/ltu.svg',
  },
  {
    name: 'Luxembourg',
    alpha2Code: 'LU',
    callingCodes: ['352'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/lux.svg',
  },
  {
    name: 'Macao',
    alpha2Code: 'MO',
    callingCodes: ['853'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/mac.svg',
  },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    alpha2Code: 'MK',
    callingCodes: ['389'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/mkd.svg',
  },
  {
    name: 'Madagascar',
    alpha2Code: 'MG',
    callingCodes: ['261'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/mdg.svg',
  },
  {
    name: 'Malawi',
    alpha2Code: 'MW',
    callingCodes: ['265'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/mwi.svg',
  },
  {
    name: 'Malaysia',
    alpha2Code: 'MY',
    callingCodes: ['60'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/mys.svg',
  },
  {
    name: 'Maldives',
    alpha2Code: 'MV',
    callingCodes: ['960'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/mdv.svg',
  },
  {
    name: 'Mali',
    alpha2Code: 'ML',
    callingCodes: ['223'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/mli.svg',
  },
  {
    name: 'Malta',
    alpha2Code: 'MT',
    callingCodes: ['356'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/mlt.svg',
  },
  {
    name: 'Marshall Islands',
    alpha2Code: 'MH',
    callingCodes: ['692'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+12:00'],
    flag: 'https://restcountries.eu/data/mhl.svg',
  },
  {
    name: 'Martinique',
    alpha2Code: 'MQ',
    callingCodes: ['596'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/mtq.svg',
  },
  {
    name: 'Mauritania',
    alpha2Code: 'MR',
    callingCodes: ['222'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/mrt.svg',
  },
  {
    name: 'Mauritius',
    alpha2Code: 'MU',
    callingCodes: ['230'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+04:00'],
    flag: 'https://restcountries.eu/data/mus.svg',
  },
  {
    name: 'Mayotte',
    alpha2Code: 'YT',
    callingCodes: ['262'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/myt.svg',
  },
  {
    name: 'Mexico',
    alpha2Code: 'MX',
    callingCodes: ['52'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-08:00', 'UTC-07:00', 'UTC-06:00'],
    flag: 'https://restcountries.eu/data/mex.svg',
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2Code: 'FM',
    callingCodes: ['691'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+10:00', 'UTC+11'],
    flag: 'https://restcountries.eu/data/fsm.svg',
  },
  {
    name: 'Moldova (Republic of)',
    alpha2Code: 'MD',
    callingCodes: ['373'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/mda.svg',
  },
  {
    name: 'Monaco',
    alpha2Code: 'MC',
    callingCodes: ['377'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/mco.svg',
  },
  {
    name: 'Mongolia',
    alpha2Code: 'MN',
    callingCodes: ['976'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+07:00', 'UTC+08:00'],
    flag: 'https://restcountries.eu/data/mng.svg',
  },
  {
    name: 'Montenegro',
    alpha2Code: 'ME',
    callingCodes: ['382'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/mne.svg',
  },
  {
    name: 'Montserrat',
    alpha2Code: 'MS',
    callingCodes: ['1664'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/msr.svg',
  },
  {
    name: 'Morocco',
    alpha2Code: 'MA',
    callingCodes: ['212'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/mar.svg',
  },
  {
    name: 'Mozambique',
    alpha2Code: 'MZ',
    callingCodes: ['258'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/moz.svg',
  },
  {
    name: 'Myanmar',
    alpha2Code: 'MM',
    callingCodes: ['95'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+06:30'],
    flag: 'https://restcountries.eu/data/mmr.svg',
  },
  {
    name: 'Namibia',
    alpha2Code: 'NA',
    callingCodes: ['264'],
    region: 'Africa',
    subregion: 'Southern Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/nam.svg',
  },
  {
    name: 'Nauru',
    alpha2Code: 'NR',
    callingCodes: ['674'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+12:00'],
    flag: 'https://restcountries.eu/data/nru.svg',
  },
  {
    name: 'Nepal',
    alpha2Code: 'NP',
    callingCodes: ['977'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+05:45'],
    flag: 'https://restcountries.eu/data/npl.svg',
  },
  {
    name: 'Netherlands',
    alpha2Code: 'NL',
    callingCodes: ['31'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC-04:00', 'UTC+01:00'],
    flag: 'https://restcountries.eu/data/nld.svg',
  },
  {
    name: 'New Caledonia',
    alpha2Code: 'NC',
    callingCodes: ['687'],
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: ['UTC+11:00'],
    flag: 'https://restcountries.eu/data/ncl.svg',
  },
  {
    name: 'New Zealand',
    alpha2Code: 'NZ',
    callingCodes: ['64'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    timezones: [
      'UTC-11:00',
      'UTC-10:00',
      'UTC+12:00',
      'UTC+12:45',
      'UTC+13:00',
    ],
    flag: 'https://restcountries.eu/data/nzl.svg',
  },
  {
    name: 'Nicaragua',
    alpha2Code: 'NI',
    callingCodes: ['505'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-06:00'],
    flag: 'https://restcountries.eu/data/nic.svg',
  },
  {
    name: 'Niger',
    alpha2Code: 'NE',
    callingCodes: ['227'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/ner.svg',
  },
  {
    name: 'Nigeria',
    alpha2Code: 'NG',
    callingCodes: ['234'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/nga.svg',
  },
  {
    name: 'Niue',
    alpha2Code: 'NU',
    callingCodes: ['683'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC-11:00'],
    flag: 'https://restcountries.eu/data/niu.svg',
  },
  {
    name: 'Norfolk Island',
    alpha2Code: 'NF',
    callingCodes: ['672'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    timezones: ['UTC+11:30'],
    flag: 'https://restcountries.eu/data/nfk.svg',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: 'KP',
    callingCodes: ['850'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+09:00'],
    flag: 'https://restcountries.eu/data/prk.svg',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
    callingCodes: ['1670'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+10:00'],
    flag: 'https://restcountries.eu/data/mnp.svg',
  },
  {
    name: 'Norway',
    alpha2Code: 'NO',
    callingCodes: ['47'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/nor.svg',
  },
  {
    name: 'Oman',
    alpha2Code: 'OM',
    callingCodes: ['968'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+04:00'],
    flag: 'https://restcountries.eu/data/omn.svg',
  },
  {
    name: 'Pakistan',
    alpha2Code: 'PK',
    callingCodes: ['92'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/pak.svg',
  },
  {
    name: 'Palau',
    alpha2Code: 'PW',
    callingCodes: ['680'],
    region: 'Oceania',
    subregion: 'Micronesia',
    timezones: ['UTC+09:00'],
    flag: 'https://restcountries.eu/data/plw.svg',
  },
  {
    name: 'Palestine, State of',
    alpha2Code: 'PS',
    callingCodes: ['970'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/pse.svg',
  },
  {
    name: 'Panama',
    alpha2Code: 'PA',
    callingCodes: ['507'],
    region: 'Americas',
    subregion: 'Central America',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/pan.svg',
  },
  {
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
    callingCodes: ['675'],
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: ['UTC+10:00'],
    flag: 'https://restcountries.eu/data/png.svg',
  },
  {
    name: 'Paraguay',
    alpha2Code: 'PY',
    callingCodes: ['595'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/pry.svg',
  },
  {
    name: 'Peru',
    alpha2Code: 'PE',
    callingCodes: ['51'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-05:00'],
    flag: 'https://restcountries.eu/data/per.svg',
  },
  {
    name: 'Philippines',
    alpha2Code: 'PH',
    callingCodes: ['63'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/phl.svg',
  },
  {
    name: 'Pitcairn',
    alpha2Code: 'PN',
    callingCodes: ['64'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC-08:00'],
    flag: 'https://restcountries.eu/data/pcn.svg',
  },
  {
    name: 'Poland',
    alpha2Code: 'PL',
    callingCodes: ['48'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/pol.svg',
  },
  {
    name: 'Portugal',
    alpha2Code: 'PT',
    callingCodes: ['351'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC-01:00', 'UTC'],
    flag: 'https://restcountries.eu/data/prt.svg',
  },
  {
    name: 'Puerto Rico',
    alpha2Code: 'PR',
    callingCodes: ['1787', '1939'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/pri.svg',
  },
  {
    name: 'Qatar',
    alpha2Code: 'QA',
    callingCodes: ['974'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/qat.svg',
  },
  {
    name: 'Republic of Kosovo',
    alpha2Code: 'XK',
    callingCodes: ['383'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/kos.svg',
  },
  {
    name: 'Réunion',
    alpha2Code: 'RE',
    callingCodes: ['262'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+04:00'],
    flag: 'https://restcountries.eu/data/reu.svg',
  },
  {
    name: 'Romania',
    alpha2Code: 'RO',
    callingCodes: ['40'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/rou.svg',
  },
  {
    name: 'Russian Federation',
    alpha2Code: 'RU',
    callingCodes: ['7'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: [
      'UTC+03:00',
      'UTC+04:00',
      'UTC+06:00',
      'UTC+07:00',
      'UTC+08:00',
      'UTC+09:00',
      'UTC+10:00',
      'UTC+11:00',
      'UTC+12:00',
    ],
    flag: 'https://restcountries.eu/data/rus.svg',
  },
  {
    name: 'Rwanda',
    alpha2Code: 'RW',
    callingCodes: ['250'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/rwa.svg',
  },
  {
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
    callingCodes: ['590'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/blm.svg',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2Code: 'SH',
    callingCodes: ['290'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC+00:00'],
    flag: 'https://restcountries.eu/data/shn.svg',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
    callingCodes: ['1869'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/kna.svg',
  },
  {
    name: 'Saint Lucia',
    alpha2Code: 'LC',
    callingCodes: ['1758'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/lca.svg',
  },
  {
    name: 'Saint Martin (French part)',
    alpha2Code: 'MF',
    callingCodes: ['590'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/maf.svg',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
    callingCodes: ['508'],
    region: 'Americas',
    subregion: 'Northern America',
    timezones: ['UTC-03:00'],
    flag: 'https://restcountries.eu/data/spm.svg',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
    callingCodes: ['1784'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/vct.svg',
  },
  {
    name: 'Samoa',
    alpha2Code: 'WS',
    callingCodes: ['685'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC+13:00'],
    flag: 'https://restcountries.eu/data/wsm.svg',
  },
  {
    name: 'San Marino',
    alpha2Code: 'SM',
    callingCodes: ['378'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/smr.svg',
  },
  {
    name: 'Sao Tome and Principe',
    alpha2Code: 'ST',
    callingCodes: ['239'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/stp.svg',
  },
  {
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
    callingCodes: ['966'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/sau.svg',
  },
  {
    name: 'Senegal',
    alpha2Code: 'SN',
    callingCodes: ['221'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/sen.svg',
  },
  {
    name: 'Serbia',
    alpha2Code: 'RS',
    callingCodes: ['381'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/srb.svg',
  },
  {
    name: 'Seychelles',
    alpha2Code: 'SC',
    callingCodes: ['248'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+04:00'],
    flag: 'https://restcountries.eu/data/syc.svg',
  },
  {
    name: 'Sierra Leone',
    alpha2Code: 'SL',
    callingCodes: ['232'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/sle.svg',
  },
  {
    name: 'Singapore',
    alpha2Code: 'SG',
    callingCodes: ['65'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/sgp.svg',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2Code: 'SX',
    callingCodes: ['1721'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/sxm.svg',
  },
  {
    name: 'Slovakia',
    alpha2Code: 'SK',
    callingCodes: ['421'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/svk.svg',
  },
  {
    name: 'Slovenia',
    alpha2Code: 'SI',
    callingCodes: ['386'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/svn.svg',
  },
  {
    name: 'Solomon Islands',
    alpha2Code: 'SB',
    callingCodes: ['677'],
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: ['UTC+11:00'],
    flag: 'https://restcountries.eu/data/slb.svg',
  },
  {
    name: 'Somalia',
    alpha2Code: 'SO',
    callingCodes: ['252'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/som.svg',
  },
  {
    name: 'South Africa',
    alpha2Code: 'ZA',
    callingCodes: ['27'],
    region: 'Africa',
    subregion: 'Southern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/zaf.svg',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2Code: 'GS',
    callingCodes: ['500'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-02:00'],
    flag: 'https://restcountries.eu/data/sgs.svg',
  },
  {
    name: 'Korea (Republic of)',
    alpha2Code: 'KR',
    callingCodes: ['82'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+09:00'],
    flag: 'https://restcountries.eu/data/kor.svg',
  },
  {
    name: 'South Sudan',
    alpha2Code: 'SS',
    callingCodes: ['211'],
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/ssd.svg',
  },
  {
    name: 'Spain',
    alpha2Code: 'ES',
    callingCodes: ['34'],
    region: 'Europe',
    subregion: 'Southern Europe',
    timezones: ['UTC', 'UTC+01:00'],
    flag: 'https://restcountries.eu/data/esp.svg',
  },
  {
    name: 'Sri Lanka',
    alpha2Code: 'LK',
    callingCodes: ['94'],
    region: 'Asia',
    subregion: 'Southern Asia',
    timezones: ['UTC+05:30'],
    flag: 'https://restcountries.eu/data/lka.svg',
  },
  {
    name: 'Sudan',
    alpha2Code: 'SD',
    callingCodes: ['249'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/sdn.svg',
  },
  {
    name: 'Suriname',
    alpha2Code: 'SR',
    callingCodes: ['597'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-03:00'],
    flag: 'https://restcountries.eu/data/sur.svg',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
    callingCodes: ['4779'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/sjm.svg',
  },
  {
    name: 'Swaziland',
    alpha2Code: 'SZ',
    callingCodes: ['268'],
    region: 'Africa',
    subregion: 'Southern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/swz.svg',
  },
  {
    name: 'Sweden',
    alpha2Code: 'SE',
    callingCodes: ['46'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/swe.svg',
  },
  {
    name: 'Switzerland',
    alpha2Code: 'CH',
    callingCodes: ['41'],
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/che.svg',
  },
  {
    name: 'Syrian Arab Republic',
    alpha2Code: 'SY',
    callingCodes: ['963'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/syr.svg',
  },
  {
    name: 'Taiwan',
    alpha2Code: 'TW',
    callingCodes: ['886'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    timezones: ['UTC+08:00'],
    flag: 'https://restcountries.eu/data/twn.svg',
  },
  {
    name: 'Tajikistan',
    alpha2Code: 'TJ',
    callingCodes: ['992'],
    region: 'Asia',
    subregion: 'Central Asia',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/tjk.svg',
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2Code: 'TZ',
    callingCodes: ['255'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/tza.svg',
  },
  {
    name: 'Thailand',
    alpha2Code: 'TH',
    callingCodes: ['66'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+07:00'],
    flag: 'https://restcountries.eu/data/tha.svg',
  },
  {
    name: 'Timor-Leste',
    alpha2Code: 'TL',
    callingCodes: ['670'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+09:00'],
    flag: 'https://restcountries.eu/data/tls.svg',
  },
  {
    name: 'Togo',
    alpha2Code: 'TG',
    callingCodes: ['228'],
    region: 'Africa',
    subregion: 'Western Africa',
    timezones: ['UTC'],
    flag: 'https://restcountries.eu/data/tgo.svg',
  },
  {
    name: 'Tokelau',
    alpha2Code: 'TK',
    callingCodes: ['690'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC+13:00'],
    flag: 'https://restcountries.eu/data/tkl.svg',
  },
  {
    name: 'Tonga',
    alpha2Code: 'TO',
    callingCodes: ['676'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC+13:00'],
    flag: 'https://restcountries.eu/data/ton.svg',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
    callingCodes: ['1868'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/tto.svg',
  },
  {
    name: 'Tunisia',
    alpha2Code: 'TN',
    callingCodes: ['216'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC+01:00'],
    flag: 'https://restcountries.eu/data/tun.svg',
  },
  {
    name: 'Turkey',
    alpha2Code: 'TR',
    callingCodes: ['90'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/tur.svg',
  },
  {
    name: 'Turkmenistan',
    alpha2Code: 'TM',
    callingCodes: ['993'],
    region: 'Asia',
    subregion: 'Central Asia',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/tkm.svg',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
    callingCodes: ['1649'],
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/tca.svg',
  },
  {
    name: 'Tuvalu',
    alpha2Code: 'TV',
    callingCodes: ['688'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC+12:00'],
    flag: 'https://restcountries.eu/data/tuv.svg',
  },
  {
    name: 'Uganda',
    alpha2Code: 'UG',
    callingCodes: ['256'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/uga.svg',
  },
  {
    name: 'Ukraine',
    alpha2Code: 'UA',
    callingCodes: ['380'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/ukr.svg',
  },
  {
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
    callingCodes: ['971'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+04'],
    flag: 'https://restcountries.eu/data/are.svg',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alpha2Code: 'GB',
    callingCodes: ['44'],
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: [
      'UTC-08:00',
      'UTC-05:00',
      'UTC-04:00',
      'UTC-03:00',
      'UTC-02:00',
      'UTC',
      'UTC+01:00',
      'UTC+02:00',
      'UTC+06:00',
    ],
    flag: 'https://restcountries.eu/data/gbr.svg',
  },
  {
    name: 'United States of America',
    alpha2Code: 'US',
    callingCodes: ['1'],
    region: 'Americas',
    subregion: 'Northern America',
    timezones: [
      'UTC-12:00',
      'UTC-11:00',
      'UTC-10:00',
      'UTC-09:00',
      'UTC-08:00',
      'UTC-07:00',
      'UTC-06:00',
      'UTC-05:00',
      'UTC-04:00',
      'UTC+10:00',
      'UTC+12:00',
    ],
    flag: 'https://restcountries.eu/data/usa.svg',
  },
  {
    name: 'Uruguay',
    alpha2Code: 'UY',
    callingCodes: ['598'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-03:00'],
    flag: 'https://restcountries.eu/data/ury.svg',
  },
  {
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
    callingCodes: ['998'],
    region: 'Asia',
    subregion: 'Central Asia',
    timezones: ['UTC+05:00'],
    flag: 'https://restcountries.eu/data/uzb.svg',
  },
  {
    name: 'Vanuatu',
    alpha2Code: 'VU',
    callingCodes: ['678'],
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: ['UTC+11:00'],
    flag: 'https://restcountries.eu/data/vut.svg',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha2Code: 'VE',
    callingCodes: ['58'],
    region: 'Americas',
    subregion: 'South America',
    timezones: ['UTC-04:00'],
    flag: 'https://restcountries.eu/data/ven.svg',
  },
  {
    name: 'Viet Nam',
    alpha2Code: 'VN',
    callingCodes: ['84'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    timezones: ['UTC+07:00'],
    flag: 'https://restcountries.eu/data/vnm.svg',
  },
  {
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
    callingCodes: ['681'],
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: ['UTC+12:00'],
    flag: 'https://restcountries.eu/data/wlf.svg',
  },
  {
    name: 'Western Sahara',
    alpha2Code: 'EH',
    callingCodes: ['212'],
    region: 'Africa',
    subregion: 'Northern Africa',
    timezones: ['UTC+00:00'],
    flag: 'https://restcountries.eu/data/esh.svg',
  },
  {
    name: 'Yemen',
    alpha2Code: 'YE',
    callingCodes: ['967'],
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: ['UTC+03:00'],
    flag: 'https://restcountries.eu/data/yem.svg',
  },
  {
    name: 'Zambia',
    alpha2Code: 'ZM',
    callingCodes: ['260'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/zmb.svg',
  },
  {
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
    callingCodes: ['263'],
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: ['UTC+02:00'],
    flag: 'https://restcountries.eu/data/zwe.svg',
  },
];

export type TypeCountry = {
  name: string;
  alpha2Code: string;
  callingCodes: Array<string>;
  region: string;
  subregion: string;
  timezones: Array<string>;
  flag: string;
};
