import Head from 'next/head';
import OrganizationIntro from '../../components/Organization/OrganizationsIntro/OrganizationIntro';
import styles from '../../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Organizations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Main}>
        <OrganizationIntro />
      </main>
    </div>
  );
}
