import { useState } from 'react';
import Head from 'next/head';
import { Button, createStyles, makeStyles, Theme } from '@material-ui/core';
import Backdrop from '@material-ui/core/Backdrop';
import { useAuth } from '../../context/authContext';
import Aux from '../../hoc/Auxiliary/Auxiliary';
import BasicUserData from '../../components/Auth/BasicUserData';
import AddGames from '../../components/Auth/AddGames';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    buttonContainer: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    button: {
      margin: 30,
    },
    backdrop: {
      zIndex: theme.zIndex.drawer + 1,
      color: '#fff',
      background: theme.palette.background.paper,
    },
  })
);

export default function Home() {
  const styles = useStyles();
  const [pageNumber, setPageNumber] = useState(1);
  const {
    signInByFacebook,
    signInByGoogle,
    isAuthBackdropOpen,
    setIsAuthBackdropOpen,
  } = useAuth();
  return (
    <Aux>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.buttonContainer}>
        <Button
          variant="contained"
          color="primary"
          onClick={signInByFacebook}
          className={styles.button}
        >
          <h3>Continue with Facebook</h3>
        </Button>
        <Button
          variant="contained"
          color="secondary"
          onClick={signInByGoogle}
          className={styles.button}
        >
          <h3>Continue With Google</h3>
        </Button>
        <Backdrop className={styles.backdrop} open={isAuthBackdropOpen}>
          {
            {
              1: <BasicUserData setPageNumber={setPageNumber} />,
              2: <AddGames setPageNumber={setPageNumber} />,
            }[pageNumber]
          }
        </Backdrop>
      </div>
    </Aux>
  );
}
