import Head from 'next/head';
import { Button, createStyles, makeStyles, Theme } from '@material-ui/core';
import { useAuth } from '../../context/authContext';
import Aux from '../../hoc/Auxiliary/Auxiliary';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    buttonContainer: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    button: {
      margin: 30,
    },
  })
);

export default function Home() {
  const styles = useStyles();
  const { signInByFacebook, signInByGoogle } = useAuth();
  return (
    <Aux>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.buttonContainer}>
        <Button
          variant="contained"
          color="primary"
          onClick={signInByFacebook}
          className={styles.button}
        >
          <h3>Continue with Facebook</h3>
        </Button>
        <Button
          variant="contained"
          color="secondary"
          onClick={signInByGoogle}
          className={styles.button}
        >
          <h3>Continue With Google</h3>
        </Button>
      </div>
    </Aux>
  );
}
