import { useState } from 'react';
import Head from 'next/head';
import { createStyles, makeStyles, Theme } from '@material-ui/core';
import { useAuth } from '../../context/authContext';
import Aux from '../../hoc/Auxiliary/Auxiliary';
import AddGames from '../../components/Auth/AddGames';
import AuthButtons from '../../components/Auth/AuthButtons';
import BasicForm from '../../components/Auth/BasicForm';
import { UserData } from '../../utilities/types';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    container: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
    },
  })
);

const inititalValues: UserData = {
  uid: '',
  username: '',
  email: '',
  country: '',
  dob: new Date('2014-08-18T21:11:54'),
  phoneNumber: '',
};

export default function Home() {
  const styles = useStyles();
  const { authPageNumber } = useAuth();
  const [userData, setUserData] = useState(inititalValues);
  return (
    <Aux>
      <Head>
        <title>Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {
          {
            1: <AuthButtons />,
            2: <BasicForm userData={userData} setUserData={setUserData} />,
            3: <AddGames isUpdating={false} username={userData.username} />,
          }[authPageNumber]
        }
      </div>
    </Aux>
  );
}
