import Head from 'next/head';
import { useRouter } from 'next/router';
import Aux from '../../../hoc/Auxiliary/Auxiliary';
import ProfileForm from '../../../components/Profile/ProfileForm';

export default function Home() {
  const router = useRouter();
  return (
    <Aux>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileForm oldValues={router.query} push={router.push} />
    </Aux>
  );
}
