import Head from 'next/head';
import { useRouter } from 'next/router';
import Aux from '../../../hoc/Auxiliary/Auxiliary';
import ProfileForm from '../../../components/Profile/ProfileForm';

const emptyInitialValues = {
  uid: '',
  displayName: '',
  dob: '',
  country: '',
  phoneNumber: '',
  email: '',
  youtubeLink: '',
  twitchLink: '',
  facebookLink: '',
  instagramLink: '',
  twitterLink: '',
  redditLink: '',
};

export default function Home() {
  const router = useRouter();
  const oldValues = { ...emptyInitialValues, ...router.query };
  return (
    <Aux>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileForm oldValues={oldValues} push={router.push} />
    </Aux>
  );
}
