import Head from 'next/head';
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles';
import { db } from '../../../firebase/config';
import Aux from '../../../hoc/Auxiliary/Auxiliary';
import { UserData } from '../../../utilities/types';
import PersonalInfo from '../../../components/Profile/ProfileInfo';
import TeamIntro from '../../../components/Profile/TeamIntro';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    container: {
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-around',
      alignItems: 'center',
    },
  })
);

export default function Home({ userData }: { userData: UserData }) {
  const styles = useStyles();
  return (
    <Aux>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <PersonalInfo userData={userData} />
        <TeamIntro />
      </div>
    </Aux>
  );
}

export async function getServerSideProps(context: {
  params: { userId: string };
}) {
  const { userId } = context.params;
  let userData = null;
  await db
    .collection('users')
    .doc(userId)
    .get()
    .then((doc) => {
      userData = doc.data();
    })
    .catch((error) => {
      console.log('Error getting cached document:', error);
    });
  return {
    props: { userData },
  };
}
