import { useState } from 'react';
import Head from 'next/head';
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles';
import Backdrop from '@material-ui/core/Backdrop';
import CreateTeam from '../../../components/Profile/createTeam';
import { db } from '../../../firebase/config';
import Aux from '../../../hoc/Auxiliary/Auxiliary';
import { UserData, TeamType } from '../../../utilities/types';
import TeamIntro from '../../../components/Profile/TeamIntro';
import TeamItem from '../../../components/Profile/TeamItem';
import ProfileHeader from '../../../components/Profile/ProfileHeader';

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    backdrop: {
      zIndex: theme.zIndex.drawer + 1,
      width: '100%',
      background: theme.palette.background.paper,
      display: 'flex',
      flexDirection: 'column',
    },
  })
);

export default function Home({
  userData,
  teams,
}: {
  userData: UserData;
  teams: Array<TeamType>;
}) {
  const styles = useStyles();
  const [open, setOpen] = useState(false);
  const [currentTeams, setCurrentTeams] = useState(teams);
  const [selectedTeam, setSelectedTeam] = useState<TeamType | undefined>(
    undefined
  );
  const closeBackdrop = () => {
    setOpen(false);
  };
  const openBackdrop = () => {
    setOpen(true);
  };

  const removeTeam = (docId: string) => {
    const temp = currentTeams.filter((item) => {
      return docId !== item.docId;
    });
    setCurrentTeams(temp);
  };

  return (
    <Aux>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ProfileHeader userData={userData} tabNumber={1} />
        {currentTeams.length !== 0 ? (
          currentTeams.map((team, index) => {
            return (
              <TeamItem
                team={team}
                key={index}
                openBackdrop={openBackdrop}
                setSelectedTeam={setSelectedTeam}
                removeTeam={removeTeam}
              />
            );
          })
        ) : (
          <TeamIntro openBackdrop={openBackdrop} />
        )}
        <Backdrop className={styles.backdrop} open={open}>
          <CreateTeam teamData={selectedTeam} closeBackdrop={closeBackdrop} />
        </Backdrop>
      </div>
    </Aux>
  );
}

export async function getServerSideProps(context: {
  params: { userId: string };
}) {
  const { userId: uid } = context.params;
  let userData: any = null;
  await db
    .collection('users')
    .doc(uid)
    .get()
    .then((doc) => {
      userData = doc.data();
    })
    .catch((error) => {
      console.log('Error getting cached document:', error);
    });

  const teams: Array<TeamType> = [];
  if (userData) {
    await db
      .collection('teams')
      .where('players', 'array-contains-any', [userData.userId])
      .get()
      .then((querySnapshot) => {
        querySnapshot.forEach((doc) => {
          const { teamName, players, inGameLead } = doc.data();
          teams.push({ teamName, players, inGameLead, docId: doc.id });
        });
      })
      .catch((error) => {
        console.log('Error getting documents: ', error);
      });
  }

  return {
    props: { userData, teams },
  };
}
