import { useState } from 'react';
import Head from 'next/head';
import CreateTeam from '../../../components/Profile/createTeam';
import { db } from '../../../firebase/config';
import Aux from '../../../hoc/Auxiliary/Auxiliary';
import { UserData, TeamType } from '../../../utilities/types';
import TeamIntro from '../../../components/Profile/TeamIntro';
import TeamItem from '../../../components/Profile/TeamItem';
import ProfileHeader from '../../../components/Profile/ProfileHeader';
import getUser from '../../../lib/getUser';

export default function Home({
  userData,
  teams,
}: {
  userData: UserData;
  teams: Array<TeamType>;
}) {
  const [open, setOpen] = useState(false);
  const [currentTeams, setCurrentTeams] = useState(teams);
  const [selectedTeam, setSelectedTeam] = useState<TeamType | undefined>(
    undefined
  );
  const closeBackdrop = () => {
    setOpen(false);
  };
  const openBackdrop = () => {
    setOpen(true);
  };

  const removeTeam = (docId: string) => {
    const temp = currentTeams.filter((item) => {
      return docId !== item.docId;
    });
    setCurrentTeams(temp);
  };

  return (
    <Aux>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ProfileHeader userData={userData} tabNumber={1} />
        {currentTeams.length !== 0 ? (
          currentTeams.map((team, index) => {
            return (
              <TeamItem
                team={team}
                key={index}
                openBackdrop={openBackdrop}
                setSelectedTeam={setSelectedTeam}
                removeTeam={removeTeam}
              />
            );
          })
        ) : (
          <TeamIntro openBackdrop={openBackdrop} />
        )}
        <CreateTeam
          open={open}
          teamData={selectedTeam}
          closeBackdrop={closeBackdrop}
        />
      </div>
    </Aux>
  );
}

export async function getServerSideProps(context: {
  params: { userId: string };
}) {
  const { userId } = context.params;
  const userData = await getUser(userId);

  const teams: Array<TeamType> = [];
  if (userData) {
    const { username } = userData;
    await db
      .collection('teams')
      .where('players', 'array-contains-any', [username])
      .get()
      .then((querySnapshot) => {
        querySnapshot.forEach((doc) => {
          const { teamName, players, inGameLead } = doc.data();
          teams.push({ teamName, players, inGameLead, docId: doc.id });
        });
      })
      .catch((error) => {
        console.log('Error getting documents: ', error);
      });
  }

  return {
    props: { userData, teams },
  };
}
