import Head from 'next/head';
import Aux from '../hoc/Auxiliary/Auxiliary';
import classes from '../styles/Home.module.scss';
import Lottie from 'react-lottie';
import * as animationData from '../assets/LottieFiles/offline-t-rex.json';

export default function Home() {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: 'xMidYMid slice',
    },
  };

  return (
    <div>
      <Head>
        <title>Offline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Aux>
        <main className={classes.Main}>
          <h2>You are offline!</h2>
          <Lottie options={defaultOptions} height={400} width={400} />
        </main>
      </Aux>
    </div>
  );
}
