import Head from 'next/head';
import Aux from '../hoc/Auxiliary/Auxiliary';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Aux>
        <main className={styles.Main}>
          <h1>Welcome to DLord</h1>
        </main>
      </Aux>
    </div>
  );
}
